### ISSUE TITLE
Incompatible with orion-icons 2.1.5

### ISSUE THREAD

**Issue by liambrozik** [AlaskaAirlines/ods-inputtext#11]
## Describe the bug
`ods-inputtext 1.0.4` and `orion-icons 2.1.5` seem to have an incompatibility. When I try and build I get these two errors: 

`Module not found: Error: Can't resolve '@alaskaairux/icons/dist/icons/alert/error_es6.js' in '[...]/node_modules/@alaskaairux/ods-inputtext/dist'`
and
`Module not found: Error: Can't resolve '@alaskaairux/icons/dist/icons/interface/x-lg_es6.js' in '[...]/node_modules/@alaskaairux/ods-inputtext/dist'`

## To Reproduce
Install these specific versions and try and build a basic sample page.

## Expected behavior
Should not have errors.

**Comment by blackfalcon** [comment]
In the transition from Orion to Auro you may need to have both Icon libs installed as dependencies. 

Input text was updated to use the new Auro icons, so you will need to install 

```
"@alaskaairux/icons": "^3.1.1",
```

If you do not have any dependency on the legacy `"@alaskaairux/orion-icons": "^2.1.5",` lib, you can remove that from your project.
