### ISSUE TITLE
Surface value to root element 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/ods-inputtext#12]
## Is your feature request related to a problem? Please describe.

If you query `ods-inputtext` you are not able to get the value of the input itself. 

In React, a work around is 

```js
let input = useRef(null);
...
<ods-inputtext ref={input} />
...
let value = input.current.value;
```

Otherwise regular JS you can query the ID on the input itself

```js
document.querySelector("#lastName").shadowRoot.querySelector("#lastName").value
```

## Describe the solution you'd like

The value of the input should be at the surface of the element so that my simply doing a query on ods-inputtext.value would result in the value of the input in the shadow DOM. 

## Describe alternatives you've considered

See above. 

## Additional context

n/a

**Comment by geoffrey1218** [comment]
Is this really an issue? I was able to successfully make ods-inputtext a controlled input just like a regular input[type="text"] in React *without* using a ref.

```jsx
import React, { useState } from 'react';

export default function Components(props) {
  const [textInput, setTextInput] = useState('starting');
  
  const handleTextInput = (e) => {
    setTextInput(e.target.value);
  }

  return (
    <div>
      <p>Current input: {textInput}</p>
      <ods-inputtext value={textInput} onInput={handleTextInput}></ods-inputtext>
    </div>

  );
}
```

The value of the input is stored in textInput. It is successfully updated when you type in the input field.

I can also get the value of the input in vanilla JS without access the shadow root.
```js
document.querySelector('ods-inputtext').value;
```

Tested in Firefox and Chrome on Windows.

**Comment by blackfalcon** [comment]
@geoffrey1218 interesting feedback. The status of this is `in discovery` as a `type: feature`, so not labeled as a bug, but more or less a question that needed to be answered. 

From the information I was given, it seemed like there was something missing, but given your feedback, that may not be the case? 

I want to validate your code, of which I don't doubt, then get these types of examples into the demo and the docs.

**Comment by liambrozik** [comment]
I think the `useRef` solution in the original issue is an acceptable and expected way of grabbing the value of the input field in React. 

I also think the `useState` method surfaced by @geoffrey1218 is great too. It might just come down to use case as to which method is better. 

The most important part here is getting these examples (or some form of them) included in the docs as mentioned by @blackfalcon

**Comment by blackfalcon** [comment]
Creating useable demos and updating the docs will be addressed in an upcoming sprint. Thanks for all the feedback.
