### ISSUE TITLE
Unable to programmatically focus ods-inputtext

### ISSUE THREAD

**Issue by geoffrey1218** [AlaskaAirlines/ods-inputtext#13]
## Describe the bug
I am unable to call focus on ods-inputtext.

## To Reproduce
1. Render `ods-inputtext` in the browser.
2. Open the console in dev tools
3. Run `document.querySelector('ods-inputtext').focus()`
4. Check `document.activeElement` in the console. It will not be the `ods-inputtext` element

## Expected behavior
The element can be focused using Javascript.

## Environment
 - OS: Windows 10
 - Browser: Latest Chrome/Firefox
 - Package version: 1.0.4

## Additional context
Being able to programmatically focus an input is important for accessibility reasons. For instance, it is common to focus the first element with a validation error if form submission fails, or focus a form element when a modal is placed on screen.

**Comment by blackfalcon** [comment]
@geoffrey1218 do you have a fix for this? Can you provide a PR?

**Comment by geoffrey1218** [comment]
No fix yet, still need to investigate more. I have some guesses though.
