### ISSUE TITLE
on/off built-in validation

### ISSUE THREAD

**Issue by liambrozik** [AlaskaAirlines/ods-inputtext#22]
## Is your feature request related to a problem? Please describe.
The built-in input validation is happening `onblur`, which is great for some use cases. I have a use case where this is too stringent and produces a less-than-ideal user experience with unnecessary errors. Basically, we have only two input fields, but both are (obviously) required so it feels a little unnecessary to have these red errors popping up `onblur`. Ideally, I'd like to see an option where the inputs are validated only on submission of a form.

## Describe the solution you'd like
Have a boolean attribute like `noValidate` or `validation` where the developer can choose to opt out of the built-in validation and implement their own validation. This means that when the attribute is used, the inputs will only show errors when the developer populates the `error` attribute (or `customValidationMessage`, I'm not sure which one is correct here). Basically, this would allow us to override/ignore the `onblur` validation and implement our own, such as the form submission example above.

## Describe alternatives you've considered
I considered removing the required attribute from the input, but then the "(optional)" text is automatically added to the label. Furthermore, @geoffrey1218 informed me that the solution isn't as simple as removing the "(optional)" text as there are other implications with regards to the functionality of the native browser input validation.

## Additional context
This is by no means make or break for my team. We have been able to provide a decent experience with custom errors using the solution provided by Geoff in #21 so this feature is more of a lower-priority nice-to-have.

**Comment by blackfalcon** [comment]
@liambrozik I agree. I remember a conversation where we needed to support non-real-time validation events. E.g. server-side validation. 

Great call out as this is a feature that was kind of forgotten.
