### ISSUE TITLE
Auro-inputText; design

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/ods-inputtext#24]
# User story

As a designer, I want to be able to use an inputText symbol, so I can accurately design product UIs that match what the developers will use.

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [x] update the current inputText UI spec to meet Auto standards 
- [ ] once the new auro-inputText element is developed, add UI symbol, to UI Kit Master

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

- [x] Backlogged
- [x] Discovery
- [x] Design
- [x] [Review](https://github.com/AlaskaAirlines/ods-inputtext/issues/27)
- [x] [Production](https://github.com/AlaskaAirlines/ods-inputtext/issues/18)
- [x] [Symbolizing](https://github.com/AlaskaAirlines/ods-inputtext/issues/28)
- [x] Complete 

## Audit

https://github.com/AlaskaAirlines/auro/issues/124

**Comment by shelbyevans** [comment]
7/15/20- Reviewed creative with Vidal and incorporated edits to designs. Branch was created in Abstract for review of final input text designs before documentation resumes.

**Comment by blackfalcon** [comment]
Review story needs to be created and assigned to Vidal to complete.

**Comment by shelbyevans** [comment]
7/23/20 - Added encrypted credit card inputs and finalized all guidelines. In the review queue now.

**Comment by blackfalcon** [comment]
@vidalmenAS once development is complete for review, this will be reviewed by myself, you and @shelbyevans. Once dev review is complete, the component will be prepared for release. I would hope that we can release the updated symbols at the same time.

**Comment by blackfalcon** [comment]
Development of Auro version is in progress.
