### ISSUE TITLE
Auro-inputText; design 'see password' functionality

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/ods-inputtext#25]
# User story

As an Alaska Customer, I want to be able to toggle the password security, so I can see my password while entering it.

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [x] update the current inputText UI spec to meet Auto standards 
- [x] once the new auro-inputText element is developed, add UI symbol, to UI Kit Master

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

- [x] Backlogged
- [x] Discovery
- [x] Design
- [x] Review [story](https://github.com/AlaskaAirlines/ods-inputtext/issues/29)
- [x] Production
- [x] Symbolizing [story](https://github.com/AlaskaAirlines/ods-inputtext/issues/30)
- [x] Complete 

## Audit

https://github.com/AlaskaAirlines/auro/issues/124

**Comment by blackfalcon** [comment]
I am wondering if we don't need to build/design this?

https://9to5google.com/2019/08/28/microsoft-developed-reveal-password-edge-chrome/

This feature is already available in Edge. 
![db4785aa-3002-486b-8cb1-2e86f2f81084](https://user-images.githubusercontent.com/181089/88346569-83e77e00-ccfd-11ea-91ce-b2633588d0e9.jpg)

**Comment by shelbyevans** [comment]
> I am wondering if we don't need to build/design this?
> 
> https://9to5google.com/2019/08/28/microsoft-developed-reveal-password-edge-chrome/
> 
> This feature is already available in Edge.
> ![db4785aa-3002-486b-8cb1-2e86f2f81084](https://user-images.githubusercontent.com/181089/88346569-83e77e00-ccfd-11ea-91ce-b2633588d0e9.jpg)

@blackfalcon I am ok with using what is already built, as long as the design matches Auro styling.

**Comment by blackfalcon** [comment]
Edge is the only browser that supports this. It's not in Google's Canary and Webkit ¯\_(ツ)_/¯ 

I say that we build this, but I am also wondering if we can do like Edge made it work. With both the eye and the X. That way, it's not one or the other in that interface as both are warranted.

**Comment by shelbyevans** [comment]
Oh! Ok-- I can incorporate that X and the eye in the same view.  Stay tuned....
